#!/bin/bash

set -xe

openapi-generator-cli generate \
    -i api_spec.yaml \
    -g go-server \
    -o src \
    --git-user-id=jsawatzky \
    --git-repo-id=server/torrent/console-go \
    --package-name=openapi

rm -rf src/openapi
mv src/go src/openapi

for i in src/openapi/*.go; do
    echo "// Code generated by openapi generator; DO NOT EDIT." | cat - "${i}" > temp
    goimports temp > "${i}"
    rm temp
done