// Code generated by openapi generator; DO NOT EDIT.
/*
 * Torrent Console
 *
 * Specification for the torrent server console to provide an interface to tools
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// DownloadNotifyPost - Notify server of a completed download
func (s *DefaultApiService) DownloadNotifyPost(ctx context.Context, mediaType string) (ImplResponse, error) {
	// TODO - update DownloadNotifyPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(5XX, {}) or use other options such as http.Ok ...
	//return Response(5XX, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DownloadNotifyPost method not implemented")
}
