// Code generated by openapi generator; DO NOT EDIT.
/*
 * Torrent Console
 *
 * Specification for the torrent server console to provide an interface to tools
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

//Response return a ImplResponse struct filled
func Response(code int, body interface{}) ImplResponse {
	return ImplResponse{Code: code, Body: body}
}
