version: "3.3"
services:
  jenkins_app:
    build:
      context: .
      args:
        uid: $PUID
        gid: $PGID
        docker_gid: $DOCKER_GID
    hostname: jenkins.server
    networks:
      jenkins:
        ipv4_address: $JENKINS_IP_ADDR
      torrent: {}
      minecraft: {}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JENKINS_DIR}:/var/jenkins_home
    restart: unless-stopped

networks:
  jenkins:
    external:
      name: jenkins
  torrent:
    external:
      name: torrent
  minecraft:
    external:
      name: minecraft