version: "3.3"
services:
  jenkins_app:
    build:
      context: .
      args:
        uid: $PUID
        gid: $PGID
        docker_gid: $DOCKER_GID
    image: jsawatzky/jenkins
    networks:
      - jenkins
      - torrent
      - minecraft
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JENKINS_DIR}:/var/jenkins_home

  jenkins_proxy:
    image: dperson/nginx        # https://github.com/dperson/nginx
    hostname: jenkins.server
    networks:
      - jenkins
    command: ["-w", "http://jenkins_app:8080/;/"] 

networks:
  jenkins:
    external:
      name: jenkins
  torrent:
    external:
      name: torrent
  minecraft:
    external:
      name: minecraft