version: "3.3"
services:

  nordvpn:
    image: bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun
    extra_hosts:
      - "console:${CONSOLE_IP_ADDR}"
    environment:
      - USER=${NORDVPN_USER}
      - PASS=${NORDVPN_PASS}
      - TECHNOLOGY=NordLynx
      # - NETWORK=172.16.3.0/24
      - DEBUG=${NORDVPN_DEBUG}
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
    restart: unless-stopped

  rutorrent:
    image: linuxserver/rutorrent
    network_mode: service:nordvpn
    depends_on:
      - nordvpn
    environment:
      - PUID
      - PGID
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - ${RUTORRENT_CONFIG_DIR}:/config
      - ${RUTORRENT_DOWNLOADS_DIR}:/downloads
    restart: unless-stopped

  torrent_web:
    image: dperson/nginx        # https://github.com/dperson/nginx
    hostname: ui.torrent.server
    depends_on:
      - rutorrent
    command: ["-w", "http://nordvpn:80/;/"] 
    restart: unless-stopped

  console-go:
    build:
      context: ./console-go
      args:
        uid: $PUID
        gid: $PGID
    hostname: api.torrent.server
    networks:
      default:
        ipv4_address: ${CONSOLE_IP_ADDR}
    environment:
      - TWILIO_SID
      - TWILIO_TOKEN
      - TWILIO_NUMBER
      - NOTIFY_NUMBER
    volumes:
      - ${CONSOLE_HOME}:/console-home
      - ${FILEBOT_INPUT}:/mount/input
      - ${FILEBOT_MOVIE_OUTPUT}:/mount/movies
      - ${FILEBOT_TV_OUTPUT}:/mount/tvshows
    restart: unless-stopped


networks:
  default:
    external:
      name: torrent